### ISSUE TITLE
Firmware update from Phone App failed? Method for recovery?

### ISSUE THREAD

**Issue by lordneeko** [SkyRocketToys/STM8TX#1]
Hello, I think maybe the firmware update from the sky rocket app to the transmitter failed.  After it told me to power cycle the transmitter, all it does is show the red light. I can't even turn it back off. have to remove the batteries to turn it off.  I tried the "force pairing" method mentioned on the forums, but that didn't work. It goes through the beeping cycles but then just freezes after 5 seconds.

Is there a way to recover it? I have been looking through the source to see if there are any recovery modes, but don't see it. Perhaps that is a needed addition?

**Comment by dan1916** [comment]
I also run into the same issue. The latest firmware update for the TX installed via the phone is bricking the TX. It just freezes after 5 seconds! DO NOT install this latest firmware on TX.

**Comment by lordneeko** [comment]
With @tridge latest commit, this should be able to be closed if it has passed testing.

Is testing performed on this project? I don't see any test scripts or results.

**Comment by dan1916** [comment]
I also noticed @tridge pushed the last commit. What was the cause actually? And does it help unbrick a transmitter ?

**Comment by lordneeko** [comment]
He fully explained it here along with instructions to recover.

http://discuss.ardupilot.org/t/unbricking-a-skyviper-transmitter/25340

**Comment by dan1916** [comment]
I see. I don’t have mine with me anymore as I replaced with a new one. Did the fix unbrick your transmitter?

**Comment by lordneeko** [comment]
i got a replacement too. so i cannot test it. but looking at the code it is a totally reasonable fix.
